### ISSUE TITLE
paper 1.21?

### ISSUE THREAD

**Issue by robtherobz** [pick1t/DeadHead#1]
would love. currently it technically still works in 1.21, but sometimes mobs pick up head items; and when killed, heads just become player heads with no item drops.

**Comment by pick1t** [comment]
> would love. currently it technically still works in 1.21, but sometimes mobs pick up head items; and when killed, heads just become player heads with no item drops.

I have plans to update the plugin to 1.21 and actually add some new features and balances as well so everyone can tailor it for their server.

But my PC died and I am currently waiting on the replacement to get here, most likely sometime next week before I can get set back up and get a chance to tackle the update. But it is coming soon(ish)!

**Comment by robtherobz** [comment]
Dont mean to be a bother, is there any progress?

**Comment by pick1t** [comment]
> would love. currently it technically still works in 1.21, but sometimes mobs pick up head items; and when killed, heads just become player heads with no item drops.

Sorry for the long response time, just got everything sorted with my internet and PC.

Plugin has been updated.

**Comment by pick1t** [comment]
Done
